### ISSUE TITLE
Customizing Export button isn't possible

### ISSUE THREAD

**Issue by Sogl** [iusvar/grav-plugin-snappygrav#48]
Hello!

I'm trying to use your plugin in my Learn4 theme, like this:
![image](https://user-images.githubusercontent.com/7556290/60440151-dcdd0380-9c1c-11e9-81f1-ef1eb55c581f.png)

I want to customize a button and, as you can see, Ru translation is started, but I want to use a link, not button. See DOM:
![image](https://user-images.githubusercontent.com/7556290/60440346-4eb54d00-9c1d-11e9-8143-a0b2652d7283.png)

But `button` is hardcoded in php:
https://github.com/iusvar/grav-plugin-snappygrav/blob/8887150075e439d0158c9b5849f47d36c3c80fc6/snappygrav.php#L203

How can I use link <a> tag instead of <button>tag?

Also I see generated CSS-styling here, but it's disabled:
![image](https://user-images.githubusercontent.com/7556290/60440565-c2eff080-9c1d-11e9-986c-623dce29f51c.png)

Cache is cleared (I don't use it at all during development). What's wrong with this option?

**Comment by Sogl** [comment]
Ok, I did style customization with css:
```css
#top-bar #navigation {
    width: 600px;
}

#navigation .export {
    color: #1195dc;
    font-size: 17px;
    font-weight: 300;
    background-color: transparent;
    margin: 0;
    text-align: center;
    border-left: 1px solid #edeef1;
    padding: 0 1rem;
}

#navigation .export:hover {
    background: #edeef1;
    color: #0e75ad;
}
```

Next step needs to add custom classes and placeholder for create js tooltip:
![image](https://user-images.githubusercontent.com/7556290/60447653-92fc1980-9c2c-11e9-832f-d997e646c7ce.png)

Docs: https://picturepan2.github.io/spectre/components/tooltips.html#tooltips
I can add custom attributes and classes only in php now.
