### ISSUE TITLE
Validation failed: btn_plugin_bg_color

### ISSUE THREAD

**Issue by BryanButler** [iusvar/grav-plugin-snappygrav#55]
Hello, I was having an issue with this plugin working correctly at exporting individual pages, but by changing the collection_options: '@root.descendants' in the admin interface it began to work.

The issue was getting that value to save. There are from what I can tell 4 variables in snappygrav.yaml that aren't in the blueprints.yaml or en.yaml that caused it to break for me, and an additional variable I had to save all together. I had to add each variable to en.yaml and blueprints.yaml and make an admin interface to save them before it would allow me to get past the validation failed error.

en.yaml addition:
```
BTN_BG_COLOR: Background Button Color
BTN_PLUGIN_BG_COLOR: Background Button Color
BTN_PLUGIN_COLOR: Button Text Color
BTN_PLUGIN_HOVER_BG_COLOR: Button Background Hover Color
BTN_PLUGIN_HOVER_COLOR: Button Text Hover Color
```

And to add each to the blueprints.yaml I followed up with a copy of btn_cancel_color for each one in blueprints.yaml

```
            btn_plugin_bg_color:
              type: select
              label: PLUGIN_SNAPPYGRAV.BTN_PLUGIN_BG_COLOR
              size: small
              default: green
              options:
                default: PLUGIN_SNAPPYGRAV.DEFAULT
                blue: PLUGIN_SNAPPYGRAV.BLUE
                green: PLUGIN_SNAPPYGRAV.GREEN
                red: PLUGIN_SNAPPYGRAV.RED
                orange: PLUGIN_SNAPPYGRAV.ORANGE
                purple: PLUGIN_SNAPPYGRAV.PURPLE
                dark: PLUGIN_SNAPPYGRAV.DARK
                gray: PLUGIN_SNAPPYGRAV.GRAY
              help: EXPORT.BTN_EXPORT_HELP
            
            btn_bg_color:
              type: select
              label: PLUGIN_SNAPPYGRAV.BTN_BG_COLOR
              size: small
              default: green
              options:
                default: PLUGIN_SNAPPYGRAV.DEFAULT
                blue: PLUGIN_SNAPPYGRAV.BLUE
                green: PLUGIN_SNAPPYGRAV.GREEN
                red: PLUGIN_SNAPPYGRAV.RED
                orange: PLUGIN_SNAPPYGRAV.ORANGE
                purple: PLUGIN_SNAPPYGRAV.PURPLE
                dark: PLUGIN_SNAPPYGRAV.DARK
                gray: PLUGIN_SNAPPYGRAV.GRAY
              help: EXPORT.BTN_EXPORT_HELP
            
            btn_plugin_color:
              type: select
              label: PLUGIN_SNAPPYGRAV.BTN_PLUGIN_COLOR
              size: small
              default: green
              options:
                default: PLUGIN_SNAPPYGRAV.DEFAULT
                blue: PLUGIN_SNAPPYGRAV.BLUE
                green: PLUGIN_SNAPPYGRAV.GREEN
                red: PLUGIN_SNAPPYGRAV.RED
                orange: PLUGIN_SNAPPYGRAV.ORANGE
                purple: PLUGIN_SNAPPYGRAV.PURPLE
                dark: PLUGIN_SNAPPYGRAV.DARK
                gray: PLUGIN_SNAPPYGRAV.GRAY
              help: EXPORT.BTN_EXPORT_HELP

            btn_plugin_hover_bg_color:
              type: select
              label: PLUGIN_SNAPPYGRAV.BTN_PLUGIN_HOVER_BG_COLOR
              size: small
              default: green
              options:
                default: PLUGIN_SNAPPYGRAV.DEFAULT
                blue: PLUGIN_SNAPPYGRAV.BLUE
                green: PLUGIN_SNAPPYGRAV.GREEN
                red: PLUGIN_SNAPPYGRAV.RED
                orange: PLUGIN_SNAPPYGRAV.ORANGE
                purple: PLUGIN_SNAPPYGRAV.PURPLE
                dark: PLUGIN_SNAPPYGRAV.DARK
                gray: PLUGIN_SNAPPYGRAV.GRAY
              help: EXPORT.BTN_EXPORT_HELP

            btn_plugin_hover_color:
              type: select
              label: PLUGIN_SNAPPYGRAV.BTN_PLUGIN_HOVER_COLOR
              size: small
              default: green
              options:
                default: PLUGIN_SNAPPYGRAV.DEFAULT
                blue: PLUGIN_SNAPPYGRAV.BLUE
                green: PLUGIN_SNAPPYGRAV.GREEN
                red: PLUGIN_SNAPPYGRAV.RED
                orange: PLUGIN_SNAPPYGRAV.ORANGE
                purple: PLUGIN_SNAPPYGRAV.PURPLE
                dark: PLUGIN_SNAPPYGRAV.DARK
                gray: PLUGIN_SNAPPYGRAV.GRAY
              help: EXPORT.BTN_EXPORT_HELP

```

I've listed my themes and Grav version here if you wish to try to replicate. I'm using TCPDF configuration with a Learn2 with Git sync skeleton.

- SnappyGrav: v1.9.1
- Learn2: v1.8.0
- Learn2 Git Sync: v1.5.8
- My Theme: v1.0.0
- Grav: 1.6.21

I've probably done something wrong in install and just put a band-aid on the problem, but I wanted to leave this here incase someone else has this problem and to get in contact with you.
